apiVersion: swarm.claudeflow.io/v1alpha1
kind: SwarmTask
metadata:
  name: create-real-github-repo
  namespace: default
spec:
  swarmRef: github-automation-swarm
  task: "Create a Go hello world application and upload it to a new GitHub repository"
  priority: high
  strategy: sequential
  timeout: "10m"