apiVersion: swarm.claudeflow.io/v1alpha1
kind: SwarmTask
metadata:
  name: github-app-hello-world
  namespace: default
spec:
  swarmRef: github-automation-swarm
  task: "Create a Go hello world application and upload it to a new GitHub repository using GitHub App authentication"
  priority: high
  strategy: sequential
  timeout: "10m"