apiVersion: v1
kind: Pod
metadata:
  name: test-executor
  namespace: claude-flow-swarm
spec:
  containers:
  - name: executor
    image: busybox:latest
    command: ["sh", "-c"]
    args:
    - |
      echo "🐝 Test Executor Running"
      echo "Testing basic functionality"
      while true; do
        date
        echo "Still running..."
        sleep 60
      done