apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: swarmtasks.swarm.claudeflow.io
spec:
  group: swarm.claudeflow.io
  versions:
  - name: v1alpha1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            required: ["swarmRef", "task"]
            properties:
              swarmRef:
                type: string
                description: "Reference to SwarmCluster"
              task:
                type: string
                description: "Task description"
              priority:
                type: string
                enum: ["low", "medium", "high", "critical"]
                default: "medium"
              strategy:
                type: string
                enum: ["parallel", "sequential", "adaptive"]
                default: "adaptive"
              timeout:
                type: string
                default: "30m"
              retryPolicy:
                type: object
                properties:
                  maxRetries:
                    type: integer
                    default: 3
                  backoffStrategy:
                    type: string
                    enum: ["exponential", "linear", "fixed"]
                    default: "exponential"
              subtasks:
                type: array
                items:
                  type: object
                  properties:
                    name:
                      type: string
                    description:
                      type: string
                    assignedAgent:
                      type: string
                    dependencies:
                      type: array
                      items:
                        type: string
          status:
            type: object
            properties:
              phase:
                type: string
                enum: ["Pending", "Assigned", "Running", "Completed", "Failed", "Cancelled"]
              assignedAgents:
                type: array
                items:
                  type: string
              startTime:
                type: string
              completionTime:
                type: string
              progress:
                type: integer
                minimum: 0
                maximum: 100
              results:
                type: object
                additionalProperties:
                  type: string
              conditions:
                type: array
                items:
                  type: object
                  properties:
                    type:
                      type: string
                    status:
                      type: string
                    lastTransitionTime:
                      type: string
                    reason:
                      type: string
                    message:
                      type: string
    subresources:
      status: {}
    additionalPrinterColumns:
    - name: Swarm
      type: string
      jsonPath: .spec.swarmRef
    - name: Priority
      type: string
      jsonPath: .spec.priority
    - name: Phase
      type: string
      jsonPath: .status.phase
    - name: Progress
      type: string
      jsonPath: .status.progress
    - name: Age
      type: date
      jsonPath: .metadata.creationTimestamp
  scope: Namespaced
  names:
    plural: swarmtasks
    singular: swarmtask
    kind: SwarmTask
    shortNames:
    - task
    - tasks