apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: swarmclusters.swarm.claudeflow.io
spec:
  group: swarm.claudeflow.io
  versions:
  - name: v1alpha1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            required: ["topology", "agentCount"]
            properties:
              topology:
                type: string
                enum: ["mesh", "hierarchical", "ring", "star"]
                description: "Swarm topology pattern"
              agentCount:
                type: integer
                minimum: 1
                maximum: 100
                description: "Number of agents in the swarm"
              agentTemplate:
                type: object
                properties:
                  type:
                    type: string
                    enum: ["researcher", "coder", "analyst", "tester", "coordinator", "architect", "reviewer", "optimizer", "documenter", "monitor", "specialist"]
                  capabilities:
                    type: array
                    items:
                      type: string
                  resources:
                    type: object
                    properties:
                      requests:
                        type: object
                        properties:
                          cpu:
                            type: string
                          memory:
                            type: string
                      limits:
                        type: object
                        properties:
                          cpu:
                            type: string
                          memory:
                            type: string
              taskDistribution:
                type: object
                properties:
                  strategy:
                    type: string
                    enum: ["parallel", "sequential", "adaptive", "capability-based"]
                    default: "adaptive"
                  maxTasksPerAgent:
                    type: integer
                    minimum: 1
                    default: 5
              autoScaling:
                type: object
                properties:
                  enabled:
                    type: boolean
                    default: false
                  minAgents:
                    type: integer
                    minimum: 1
                  maxAgents:
                    type: integer
                    maximum: 100
                  metrics:
                    type: array
                    items:
                      type: object
                      properties:
                        type:
                          type: string
                          enum: ["cpu", "memory", "taskQueue", "responseTime"]
                        targetValue:
                          type: string
          status:
            type: object
            properties:
              phase:
                type: string
                enum: ["Pending", "Creating", "Running", "Scaling", "Updating", "Deleting", "Failed"]
              readyAgents:
                type: integer
              totalAgents:
                type: integer
              conditions:
                type: array
                items:
                  type: object
                  properties:
                    type:
                      type: string
                    status:
                      type: string
                    lastTransitionTime:
                      type: string
                    reason:
                      type: string
                    message:
                      type: string
              message:
                type: string
              lastUpdated:
                type: string
    subresources:
      status: {}
      scale:
        specReplicasPath: .spec.agentCount
        statusReplicasPath: .status.totalAgents
    additionalPrinterColumns:
    - name: Topology
      type: string
      jsonPath: .spec.topology
    - name: Agents
      type: string
      jsonPath: .status.readyAgents
    - name: Total
      type: string
      jsonPath: .status.totalAgents
    - name: Phase
      type: string
      jsonPath: .status.phase
    - name: Age
      type: date
      jsonPath: .metadata.creationTimestamp
  scope: Namespaced
  names:
    plural: swarmclusters
    singular: swarmcluster
    kind: SwarmCluster
    shortNames:
    - swarm
    - swarms