# permissions for end users to view swarmclusters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: swarmcluster-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: swarm-operator
    app.kubernetes.io/part-of: swarm-operator
    app.kubernetes.io/managed-by: kustomize
  name: swarmcluster-viewer-role
rules:
- apiGroups:
  - swarm.claudeflow.io
  resources:
  - swarmclusters
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - swarm.claudeflow.io
  resources:
  - swarmclusters/status
  verbs:
  - get
