# permissions for end users to edit swarmtasks.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: swarmtask-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: swarm-operator
    app.kubernetes.io/part-of: swarm-operator
    app.kubernetes.io/managed-by: kustomize
  name: swarmtask-editor-role
rules:
- apiGroups:
  - swarm.claudeflow.io
  resources:
  - swarmtasks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - swarm.claudeflow.io
  resources:
  - swarmtasks/status
  verbs:
  - get
