apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: swarmtasks.swarm.claudeflow.io
spec:
  group: swarm.claudeflow.io
  versions:
  - name: v1alpha1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            required:
            - task
            properties:
              task:
                type: string
                description: "The task description or command to execute"
              swarmRef:
                type: string
                description: "Reference to the SwarmCluster that will execute this task"
              priority:
                type: string
                enum: ["low", "medium", "high", "critical"]
                default: "medium"
                description: "Task priority level"
              strategy:
                type: string
                enum: ["parallel", "sequential", "adaptive", "balanced"]
                default: "adaptive"
                description: "Execution strategy for the task"
              timeout:
                type: string
                pattern: '^([0-9]+(\.[0-9]+)?(s|m|h))?$'
                default: "30m"
                description: "Task execution timeout"
              resume:
                type: boolean
                default: false
                description: "Whether to resume a failed task from last checkpoint"
              config:
                type: object
                description: "Enhanced configuration options"
                properties:
                  executorImage:
                    type: string
                    description: "Custom executor image to use for this task"
                  additionalSecrets:
                    type: array
                    description: "Additional secrets to mount in the task container"
                    items:
                      type: object
                      required:
                      - name
                      - mountPath
                      properties:
                        name:
                          type: string
                          description: "Name of the Kubernetes secret"
                        mountPath:
                          type: string
                          description: "Path where the secret should be mounted"
                        optional:
                          type: boolean
                          default: false
                          description: "Whether the secret is optional"
                  persistentVolumes:
                    type: array
                    description: "Persistent volumes to attach for state storage"
                    items:
                      type: object
                      required:
                      - name
                      - mountPath
                      properties:
                        name:
                          type: string
                          description: "Name identifier for the PVC"
                        mountPath:
                          type: string
                          description: "Path where the volume should be mounted"
                        storageClass:
                          type: string
                          description: "Storage class to use for the PVC"
                        size:
                          type: string
                          pattern: '^[0-9]+(\.[0-9]+)?(Mi|Gi|Ti)$'
                          default: "10Gi"
                          description: "Size of the persistent volume"
                  resources:
                    type: object
                    description: "Resource requirements for the task"
                    properties:
                      requests:
                        type: object
                        properties:
                          cpu:
                            type: string
                            pattern: '^[0-9]+(\.[0-9]+)?[m]?$'
                          memory:
                            type: string
                            pattern: '^[0-9]+(\.[0-9]+)?(Mi|Gi)$'
                      limits:
                        type: object
                        properties:
                          cpu:
                            type: string
                            pattern: '^[0-9]+(\.[0-9]+)?[m]?$'
                          memory:
                            type: string
                            pattern: '^[0-9]+(\.[0-9]+)?(Mi|Gi)$'
                  environment:
                    type: array
                    description: "Additional environment variables"
                    items:
                      type: object
                      required:
                      - name
                      properties:
                        name:
                          type: string
                        value:
                          type: string
                        valueFrom:
                          type: object
                          properties:
                            secretKeyRef:
                              type: object
                              required:
                              - name
                              - key
                              properties:
                                name:
                                  type: string
                                key:
                                  type: string
                                optional:
                                  type: boolean
                            configMapKeyRef:
                              type: object
                              required:
                              - name
                              - key
                              properties:
                                name:
                                  type: string
                                key:
                                  type: string
                                optional:
                                  type: boolean
          status:
            type: object
            properties:
              phase:
                type: string
                enum: ["Pending", "Running", "Completed", "Failed", "Suspended"]
              message:
                type: string
              startTime:
                type: string
                format: date-time
              completionTime:
                type: string
                format: date-time
              lastUpdateTime:
                type: string
                format: date-time
              jobRef:
                type: string
                description: "Reference to the Kubernetes Job executing this task"
              checkpoint:
                type: object
                description: "Checkpoint data for task resumption"
                properties:
                  step:
                    type: string
                  data:
                    type: object
                    x-kubernetes-preserve-unknown-fields: true
              conditions:
                type: array
                items:
                  type: object
                  required:
                  - type
                  - status
                  properties:
                    type:
                      type: string
                    status:
                      type: string
                      enum: ["True", "False", "Unknown"]
                    lastTransitionTime:
                      type: string
                      format: date-time
                    reason:
                      type: string
                    message:
                      type: string
    subresources:
      status: {}
    additionalPrinterColumns:
    - name: Task
      type: string
      jsonPath: .spec.task
    - name: Priority
      type: string
      jsonPath: .spec.priority
    - name: Phase
      type: string
      jsonPath: .status.phase
    - name: Age
      type: date
      jsonPath: .metadata.creationTimestamp
  scope: Namespaced
  names:
    plural: swarmtasks
    singular: swarmtask
    kind: SwarmTask
    shortNames:
    - st
    - task