apiVersion: apps/v1
kind: Deployment
metadata:
  name: swarm-operator
  namespace: swarm-system
  labels:
    app.kubernetes.io/name: swarm-operator
    app.kubernetes.io/component: controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: swarm-operator
      app.kubernetes.io/component: controller
  template:
    metadata:
      labels:
        app.kubernetes.io/name: swarm-operator
        app.kubernetes.io/component: controller
    spec:
      serviceAccountName: swarm-operator
      securityContext:
        runAsNonRoot: true
        runAsUser: 65532
        fsGroup: 65532
      containers:
      - name: operator
        image: swarm-operator:latest
        imagePullPolicy: IfNotPresent
        command:
        - /manager
        args:
        - --leader-elect
        - --metrics-bind-addr=:8080
        - --health-probe-bind-addr=:8081
        env:
        - name: OPERATOR_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        ports:
        - containerPort: 8080
          name: metrics
          protocol: TCP
        - containerPort: 8081
          name: health
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /healthz
            port: health
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /readyz
            port: health
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 128Mi
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
            - ALL
        volumeMounts:
        - name: temp
          mountPath: /tmp
      volumes:
      - name: temp
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: swarm-operator-metrics
  namespace: swarm-system
  labels:
    app.kubernetes.io/name: swarm-operator
    app.kubernetes.io/component: controller
spec:
  selector:
    app.kubernetes.io/name: swarm-operator
    app.kubernetes.io/component: controller
  ports:
  - name: metrics
    port: 8080
    targetPort: metrics
    protocol: TCP
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: swarm-operator-config
  namespace: swarm-system
data:
  config.yaml: |
    # Operator configuration
    controller:
      syncPeriod: 30s
      maxConcurrentReconciles: 10
    
    defaults:
      agent:
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
      
      topology:
        mesh:
          connectionDensity: 0.7
        hierarchical:
          levelsPerCoordinator: 3
        ring:
          bidirectional: true
        star:
          redundantCoordinators: 2
    
    metrics:
      enabled: true
      interval: 30s
    
    logging:
      level: info
      format: json