apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: swarmclusters.swarm.claudeflow.io
spec:
  group: swarm.claudeflow.io
  versions:
  - name: v1alpha1
    served: true
    storage: true
    subresources:
      status: {}
      scale:
        specReplicasPath: .spec.autoscaling.minAgents
        statusReplicasPath: .status.totalAgents
    additionalPrinterColumns:
    - name: Topology
      type: string
      jsonPath: .spec.topology
    - name: Ready
      type: integer
      jsonPath: .status.readyAgents
    - name: Total
      type: integer
      jsonPath: .status.totalAgents
    - name: Tasks
      type: integer
      jsonPath: .status.activeTasks
    - name: Phase
      type: string
      jsonPath: .status.phase
    schema:
      openAPIV3Schema:
        type: object
        properties:
          apiVersion:
            type: string
          kind:
            type: string
          metadata:
            type: object
          spec:
            type: object
            required:
            - topology
            properties:
              topology:
                type: string
                enum: ["mesh", "hierarchical", "ring", "star"]
              queenMode:
                type: string
                enum: ["centralized", "distributed"]
                default: "distributed"
              strategy:
                type: string
                enum: ["parallel", "sequential", "adaptive", "consensus"]
                default: "adaptive"
              consensusThreshold:
                type: number
                minimum: 0
                maximum: 1
                default: 0.66
              hiveMind:
                type: object
                properties:
                  enabled:
                    type: boolean
                    default: true
                  databaseSize:
                    type: string
                    default: "10Gi"
                  syncInterval:
                    type: string
                    default: "30s"
                  backupEnabled:
                    type: boolean
                    default: true
                  backupInterval:
                    type: string
                    default: "1h"
              autoscaling:
                type: object
                properties:
                  enabled:
                    type: boolean
                    default: true
                  minAgents:
                    type: integer
                    minimum: 1
                    default: 3
                  maxAgents:
                    type: integer
                    minimum: 1
                    default: 20
                  targetUtilization:
                    type: integer
                    minimum: 1
                    maximum: 100
                    default: 80
                  scaleUpThreshold:
                    type: integer
                    default: 3
                  scaleDownThreshold:
                    type: integer
                    default: 10
                  stabilizationWindow:
                    type: string
                    default: "300s"
                  topologyRatios:
                    type: object
                    additionalProperties:
                      type: integer
                  metrics:
                    type: array
                    items:
                      type: object
                      required:
                      - type
                      - target
                      properties:
                        type:
                          type: string
                          enum: ["cpu", "memory", "queue", "custom"]
                        name:
                          type: string
                        target:
                          type: string
              agentTemplate:
                type: object
                properties:
                  image:
                    type: string
                    default: "claudeflow/swarm-executor:2.0.0"
                  resources:
                    type: object
                    properties:
                      cpu:
                        type: string
                      memory:
                        type: string
                      gpu:
                        type: string
                  securityContext:
                    type: object
                    properties:
                      runAsNonRoot:
                        type: boolean
                      runAsUser:
                        type: integer
                      fsGroup:
                        type: integer
                  nodeSelector:
                    type: object
                    additionalProperties:
                      type: string
                  tolerations:
                    type: array
                    items:
                      type: object
                      properties:
                        key:
                          type: string
                        operator:
                          type: string
                        value:
                          type: string
                        effect:
                          type: string
                  affinity:
                    type: object
                    properties:
                      nodeAffinity:
                        type: object
                        properties:
                          requiredDuringScheduling:
                            type: array
                            items:
                              type: object
                              properties:
                                matchLabels:
                                  type: object
                                  additionalProperties:
                                    type: string
                      podAffinity:
                        type: object
                        properties:
                          preferredDuringScheduling:
                            type: array
                            items:
                              type: object
                              properties:
                                weight:
                                  type: integer
                                podAffinityTerm:
                                  type: object
                                  properties:
                                    labelSelector:
                                      type: object
                                      additionalProperties:
                                        type: string
                                    topologyKey:
                                      type: string
              memory:
                type: object
                properties:
                  type:
                    type: string
                    enum: ["redis", "hazelcast", "etcd"]
                    default: "redis"
                  size:
                    type: string
                    default: "2Gi"
                  replication:
                    type: integer
                    minimum: 1
                    default: 3
                  persistence:
                    type: boolean
                    default: true
                  cachePolicy:
                    type: string
                    enum: ["LRU", "LFU", "ARC"]
                    default: "LRU"
                  compression:
                    type: boolean
                    default: true
              neural:
                type: object
                properties:
                  enabled:
                    type: boolean
                    default: false
                  models:
                    type: array
                    items:
                      type: object
                      required:
                      - name
                      - type
                      - path
                      properties:
                        name:
                          type: string
                        type:
                          type: string
                          enum: ["pattern-recognition", "optimization", "prediction"]
                        path:
                          type: string
                        resources:
                          type: object
                          properties:
                            cpu:
                              type: string
                            memory:
                              type: string
                            gpu:
                              type: string
                  acceleration:
                    type: string
                    enum: ["cpu", "gpu", "wasm-simd"]
                    default: "cpu"
                  trainingEnabled:
                    type: boolean
                    default: false
              monitoring:
                type: object
                properties:
                  enabled:
                    type: boolean
                    default: true
                  metricsPort:
                    type: integer
                    default: 9090
                  tracingEnabled:
                    type: boolean
                    default: false
                  dashboardEnabled:
                    type: boolean
                    default: true
                  alertRules:
                    type: array
                    items:
                      type: object
                      required:
                      - name
                      - expression
                      - duration
                      - severity
                      properties:
                        name:
                          type: string
                        expression:
                          type: string
                        duration:
                          type: string
                        severity:
                          type: string
                          enum: ["info", "warning", "critical"]
          status:
            type: object
            properties:
              phase:
                type: string
              readyAgents:
                type: integer
              totalAgents:
                type: integer
              agentTypes:
                type: object
                additionalProperties:
                  type: integer
              activeTasks:
                type: integer
              completedTasks:
                type: integer
              hiveMindStatus:
                type: object
                properties:
                  connected:
                    type: integer
                  syncStatus:
                    type: string
                  lastSyncTime:
                    type: string
                  databaseSize:
                    type: string
              memoryStatus:
                type: object
                properties:
                  available:
                    type: string
                  used:
                    type: string
                  hitRate:
                    type: number
                  evictions:
                    type: integer
              conditions:
                type: array
                items:
                  type: object
                  properties:
                    type:
                      type: string
                    status:
                      type: string
                    lastTransitionTime:
                      type: string
                    reason:
                      type: string
                    message:
                      type: string
              lastScaleTime:
                type: string
              observedGeneration:
                type: integer
  scope: Namespaced
  names:
    plural: swarmclusters
    singular: swarmcluster
    kind: SwarmCluster
    shortNames:
    - sc