apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: swarmagents.swarm.claudeflow.io
spec:
  group: swarm.claudeflow.io
  versions:
  - name: v1alpha1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            required:
            - type
            - clusterRef
            properties:
              type:
                type: string
                enum:
                - researcher
                - coder
                - analyst
                - optimizer
                - coordinator
                - architect
                - tester
                - reviewer
                - documenter
                - monitor
                - specialist
                description: Type of agent specialization
              clusterRef:
                type: string
                description: Reference to the parent SwarmCluster
              cognitivePattern:
                type: string
                enum:
                - convergent
                - divergent
                - lateral
                - systems
                - critical
                - abstract
                - adaptive
                default: convergent
                description: Cognitive thinking pattern
              priority:
                type: integer
                minimum: 0
                maximum: 100
                default: 50
                description: Agent priority (0-100)
              maxConcurrentTasks:
                type: integer
                minimum: 1
                maximum: 10
                default: 3
                description: Maximum concurrent tasks
              hiveMindRole:
                type: string
                enum:
                - leader
                - follower
                - candidate
                default: follower
                description: Role in hive-mind consensus
              capabilities:
                type: array
                items:
                  type: string
                description: List of agent capabilities
              resources:
                type: object
                properties:
                  cpu:
                    type: string
                    pattern: '^(\d+m?|\d+\.\d+)$'
                    default: "100m"
                    description: CPU resources for the agent
                  memory:
                    type: string
                    pattern: '^(\d+[EPTGMK]i?|[0-9]+(\.[0-9]+)?[EPTGMK]?i?)$'
                    default: "128Mi"
                    description: Memory resources for the agent
                  gpu:
                    type: string
                    description: GPU resources if needed
              neuralModel:
                type: object
                properties:
                  enabled:
                    type: boolean
                    default: false
                  modelType:
                    type: string
                    enum:
                    - transformer
                    - lstm
                    - gnn
                    - hybrid
                  checkpoint:
                    type: string
                    description: Path to model checkpoint
                  trainingData:
                    type: string
                    description: Reference to training data ConfigMap
              affinity:
                type: object
                x-kubernetes-preserve-unknown-fields: true
                description: Kubernetes pod affinity rules
              tolerations:
                type: array
                items:
                  type: object
                  x-kubernetes-preserve-unknown-fields: true
                description: Kubernetes pod tolerations
              nodeSelector:
                type: object
                additionalProperties:
                  type: string
                description: Node selector for pod placement
          status:
            type: object
            properties:
              phase:
                type: string
                enum:
                - Pending
                - Initializing
                - Running
                - Training
                - Coordinating
                - Terminating
                - Failed
                - Completed
              podName:
                type: string
                description: Name of the pod running this agent
              nodeIP:
                type: string
                description: IP of the node running this agent
              startTime:
                type: string
                format: date-time
              lastActivity:
                type: string
                format: date-time
              tasksCompleted:
                type: integer
                default: 0
              tasksInProgress:
                type: integer
                default: 0
              tasksFailed:
                type: integer
                default: 0
              performance:
                type: object
                properties:
                  throughput:
                    type: number
                    description: Tasks per minute
                  accuracy:
                    type: number
                    minimum: 0
                    maximum: 1
                    description: Task completion accuracy
                  efficiency:
                    type: number
                    minimum: 0
                    maximum: 1
                    description: Resource efficiency score
              neuralStatus:
                type: object
                properties:
                  modelLoaded:
                    type: boolean
                  trainingProgress:
                    type: number
                    minimum: 0
                    maximum: 100
                  lastTrainingTime:
                    type: string
                    format: date-time
                  inferenceLatency:
                    type: string
                    description: Average inference latency
              conditions:
                type: array
                items:
                  type: object
                  required:
                  - type
                  - status
                  properties:
                    type:
                      type: string
                      enum:
                      - Ready
                      - Scheduled
                      - Healthy
                      - ResourcesAvailable
                      - NeuralModelReady
                    status:
                      type: string
                      enum:
                      - "True"
                      - "False"
                      - Unknown
                    lastTransitionTime:
                      type: string
                      format: date-time
                    reason:
                      type: string
                    message:
                      type: string
    additionalPrinterColumns:
    - name: Type
      type: string
      jsonPath: .spec.type
    - name: Cluster
      type: string
      jsonPath: .spec.clusterRef
    - name: Pattern
      type: string
      jsonPath: .spec.cognitivePattern
    - name: Phase
      type: string
      jsonPath: .status.phase
    - name: Tasks
      type: integer
      jsonPath: .status.tasksCompleted
    - name: Age
      type: date
      jsonPath: .metadata.creationTimestamp
    subresources:
      status: {}
  scope: Namespaced
  names:
    plural: swarmagents
    singular: swarmagent
    kind: SwarmAgent
    shortNames:
    - sa
    categories:
    - swarm
    - claude-flow