apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: swarmmemories.swarm.claudeflow.io
spec:
  group: swarm.claudeflow.io
  versions:
  - name: v1alpha1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            required:
            - clusterRef
            - type
            - key
            - value
            properties:
              clusterRef:
                type: string
                description: Reference to the parent SwarmCluster
              namespace:
                type: string
                default: default
                description: Memory namespace for organization
              type:
                type: string
                enum:
                - knowledge
                - experience
                - pattern
                - decision
                - metric
                description: Type of memory entry
              key:
                type: string
                minLength: 1
                maxLength: 253
                pattern: '^[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*$'
                description: Unique key for the memory entry
              value:
                type: string
                description: Memory content (JSON string)
              ttl:
                type: integer
                minimum: 0
                default: 0
                description: Time to live in seconds (0 = permanent)
              priority:
                type: integer
                minimum: 0
                maximum: 100
                default: 50
                description: Priority level for memory retention
              tags:
                type: array
                items:
                  type: string
                description: Tags for memory categorization
              sharedWith:
                type: array
                items:
                  type: string
                description: Agent types that can access this memory
              encryption:
                type: boolean
                default: false
                description: Whether to encrypt the memory value
              compression:
                type: boolean
                default: false
                description: Whether to compress the memory value
              version:
                type: integer
                minimum: 1
                default: 1
                description: Memory version for tracking updates
          status:
            type: object
            properties:
              phase:
                type: string
                enum:
                - Pending
                - Active
                - Expiring
                - Expired
                - Archived
                - Failed
              size:
                type: string
                description: Size of the memory entry
              compressed:
                type: boolean
                default: false
              encrypted:
                type: boolean
                default: false
              lastAccessed:
                type: string
                format: date-time
              accessCount:
                type: integer
                default: 0
              createdAt:
                type: string
                format: date-time
              expiresAt:
                type: string
                format: date-time
              checksum:
                type: string
                description: SHA256 checksum of the value
              conditions:
                type: array
                items:
                  type: object
                  required:
                  - type
                  - status
                  properties:
                    type:
                      type: string
                      enum:
                      - Available
                      - Replicated
                      - Indexed
                      - Encrypted
                      - Compressed
                    status:
                      type: string
                      enum:
                      - "True"
                      - "False"
                      - Unknown
                    lastTransitionTime:
                      type: string
                      format: date-time
                    reason:
                      type: string
                    message:
                      type: string
    additionalPrinterColumns:
    - name: Key
      type: string
      jsonPath: .spec.key
    - name: Type
      type: string
      jsonPath: .spec.type
    - name: Namespace
      type: string
      jsonPath: .spec.namespace
    - name: Phase
      type: string
      jsonPath: .status.phase
    - name: Size
      type: string
      jsonPath: .status.size
    - name: Accessed
      type: integer
      jsonPath: .status.accessCount
    - name: Age
      type: date
      jsonPath: .metadata.creationTimestamp
    subresources:
      status: {}
  scope: Namespaced
  names:
    plural: swarmmemories
    singular: swarmmemory
    kind: SwarmMemory
    shortNames:
    - sm
    categories:
    - swarm
    - claude-flow